CLASS ltcl_ui2json DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION SHORT FINAL.

  PRIVATE SECTION.
    METHODS test1 FOR TESTING RAISING cx_static_check.

ENDCLASS.

CLASS ltcl_ui2json IMPLEMENTATION.

  METHOD test1.
    RETURN.
  ENDMETHOD.

ENDCLASS.