CLASS cl_ixml DEFINITION PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS:
      create RETURNING VALUE(xml) TYPE REF TO if_ixml.
ENDCLASS.

CLASS cl_ixml IMPLEMENTATION.
  METHOD create.
    ASSERT 2 = 'todo'.
  ENDMETHOD.
ENDCLASS.