CLASS cx_sy_no_handler DEFINITION PUBLIC INHERITING FROM cx_no_check FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CONSTANTS cx_sy_no_handler TYPE sotr_conc VALUE 'CX_SY_NO_HANDLER'.
ENDCLASS.

CLASS cx_sy_no_handler IMPLEMENTATION.

ENDCLASS.