CLASS cl_abap_format DEFINITION PUBLIC.
  PUBLIC SECTION.
    CONSTANTS e_html_attr TYPE i VALUE 5.
    CONSTANTS e_html_text TYPE i VALUE 4.
    CONSTANTS e_url TYPE i VALUE 12.
ENDCLASS.

CLASS cl_abap_format IMPLEMENTATION.

ENDCLASS.