TYPE-POOL icon.

CONSTANTS icon_active_inactive TYPE c LENGTH 4 VALUE 'TODO'.
CONSTANTS icon_availability_check TYPE c LENGTH 4 VALUE 'TODO'.
CONSTANTS icon_include_in_selection TYPE c LENGTH 4 VALUE 'TODO'.
CONSTANTS icon_supplier TYPE c LENGTH 4 VALUE 'TODO'.
CONSTANTS icon_val_quantity_structure TYPE c LENGTH 4 VALUE 'TODO'.

CONSTANTS icon_abap TYPE c LENGTH 4 VALUE '@9U@'.
CONSTANTS icon_action_success TYPE c LENGTH 4 VALUE '@9P@'.
CONSTANTS icon_activate TYPE c LENGTH 4 VALUE '@3C@'.
CONSTANTS icon_activity TYPE c LENGTH 4 VALUE '@9Y@'.
CONSTANTS icon_add_row TYPE c LENGTH 4 VALUE '@XR@'.
CONSTANTS icon_address TYPE c LENGTH 4 VALUE '@0T@'.
CONSTANTS icon_adopt TYPE c LENGTH 4 VALUE '@IL@'.
CONSTANTS icon_alarm TYPE c LENGTH 4 VALUE '@1V@'.
CONSTANTS icon_alert TYPE c LENGTH 4 VALUE '@AG@'.
CONSTANTS icon_allow TYPE c LENGTH 4 VALUE '@8X@'.
CONSTANTS icon_annotation TYPE c LENGTH 4 VALUE '@0J@'.
CONSTANTS icon_arrow_left TYPE c LENGTH 4 VALUE '@9S@'.
CONSTANTS icon_arrow_right TYPE c LENGTH 4 VALUE '@9T@'.
CONSTANTS icon_attachment TYPE c LENGTH 4 VALUE '@FM@'.
CONSTANTS icon_background_job TYPE c LENGTH 4 VALUE '@M4@'.
CONSTANTS icon_ben_current_benefits TYPE c LENGTH 4 VALUE '@9I@'.
CONSTANTS icon_ben_termination TYPE c LENGTH 4 VALUE '@9J@'.
CONSTANTS icon_biw_info_catalog TYPE c LENGTH 4 VALUE '@6N@'.
CONSTANTS icon_biw_info_cube TYPE c LENGTH 4 VALUE '@6H@'.
CONSTANTS icon_biw_monitor TYPE c LENGTH 4 VALUE '@6P@'.
CONSTANTS icon_biw_report TYPE c LENGTH 4 VALUE '@6T@'.
CONSTANTS icon_biw_scheduler TYPE c LENGTH 4 VALUE '@6Q@'.
CONSTANTS icon_biw_source_sys_r3 TYPE c LENGTH 4 VALUE '@6K@'.
CONSTANTS icon_booking_ok TYPE c LENGTH 4 VALUE '@B1@'.
CONSTANTS icon_booking_stop TYPE c LENGTH 4 VALUE '@B2@'.
CONSTANTS icon_breakpoint TYPE c LENGTH 4 VALUE '@3U@'.
CONSTANTS icon_breakpoint_disable TYPE c LENGTH 4 VALUE '@UR@'.
CONSTANTS icon_businav_process TYPE c LENGTH 4 VALUE '@4S@'.
CONSTANTS icon_businav_processmatrix TYPE c LENGTH 4 VALUE '@4T@'.
CONSTANTS icon_businav_value_chain TYPE c LENGTH 4 VALUE '@5G@'.
CONSTANTS icon_bw_info_cube_ina TYPE c LENGTH 4 VALUE '@F4@'.
CONSTANTS icon_bw_ra_setting_active TYPE c LENGTH 4 VALUE '@O1@'.
CONSTANTS icon_bw_ra_setting_inactive TYPE c LENGTH 4 VALUE '@O2@'.
CONSTANTS icon_calculation TYPE c LENGTH 4 VALUE '@0M@'.
CONSTANTS icon_cancel TYPE c LENGTH 4 VALUE '@0W@'.
CONSTANTS icon_change TYPE c LENGTH 4 VALUE '@0Z@'.
CONSTANTS icon_change_text TYPE c LENGTH 4 VALUE '@0Q@'.
CONSTANTS icon_check TYPE c LENGTH 4 VALUE '@38@'.
CONSTANTS icon_checkbox TYPE c LENGTH 4 VALUE '@R7@'.
CONSTANTS icon_checked TYPE c LENGTH 4 VALUE '@01@'.
CONSTANTS icon_claim TYPE c LENGTH 4 VALUE '@FH@'.
CONSTANTS icon_client_breakpoint TYPE c LENGTH 4 VALUE '@VD@'.
CONSTANTS icon_close TYPE c LENGTH 4 VALUE '@3X@'.
CONSTANTS icon_closed_folder TYPE c LENGTH 4 VALUE '@FN@'.
CONSTANTS icon_collapse TYPE c LENGTH 4 VALUE '@3T@'.
CONSTANTS icon_color TYPE c LENGTH 4 VALUE '@G3@'.
CONSTANTS icon_column_left TYPE c LENGTH 4 VALUE '@0D@'.
CONSTANTS icon_column_right TYPE c LENGTH 4 VALUE '@0E@'.
CONSTANTS icon_compare TYPE c LENGTH 4 VALUE '@46@'.
CONSTANTS icon_complete TYPE c LENGTH 4 VALUE '@DF@'.
CONSTANTS icon_composite_activitygroup TYPE c LENGTH 4 VALUE '@M7@'.
CONSTANTS icon_configuration TYPE c LENGTH 4 VALUE '@BX@'.
CONSTANTS icon_connect TYPE c LENGTH 4 VALUE '@GB@'.
CONSTANTS icon_connection_object TYPE c LENGTH 4 VALUE '@PQ@'.
CONSTANTS icon_convert TYPE c LENGTH 4 VALUE '@3H@'.
CONSTANTS icon_copy_object TYPE c LENGTH 4 VALUE '@14@'.
CONSTANTS icon_cost_components TYPE c LENGTH 4 VALUE '@Q7@'.
CONSTANTS icon_create TYPE c LENGTH 4 VALUE '@0Y@'.
CONSTANTS icon_create_copy TYPE c LENGTH 4 VALUE '@EZ@'.
CONSTANTS icon_create_note TYPE c LENGTH 4 VALUE '@0K@'.
CONSTANTS icon_create_text TYPE c LENGTH 4 VALUE '@0O@'.
CONSTANTS icon_customer TYPE c LENGTH 4 VALUE '@A0@'.
CONSTANTS icon_customs TYPE c LENGTH 4 VALUE '@D7@'.
CONSTANTS icon_cut_relation TYPE c LENGTH 4 VALUE '@53@'.
CONSTANTS icon_data_area_collapse TYPE c LENGTH 4 VALUE '@K2@'.
CONSTANTS icon_data_area_expand TYPE c LENGTH 4 VALUE '@K1@'.
CONSTANTS icon_database_table TYPE c LENGTH 4 VALUE '@PO@'.
CONSTANTS icon_date TYPE c LENGTH 4 VALUE '@1U@'.
CONSTANTS icon_deactivate TYPE c LENGTH 4 VALUE '@8I@'.
CONSTANTS icon_defect TYPE c LENGTH 4 VALUE '@F1@'.
CONSTANTS icon_delete TYPE c LENGTH 4 VALUE '@11@'.
CONSTANTS icon_delete_favorites TYPE c LENGTH 4 VALUE '@ES@'.
CONSTANTS icon_delete_row TYPE c LENGTH 4 VALUE '@18@'.
CONSTANTS icon_delete_template TYPE c LENGTH 4 VALUE '@Q0@'.
CONSTANTS icon_delivery_inbound TYPE c LENGTH 4 VALUE '@PG@'.
CONSTANTS icon_delivery_no_confirmation TYPE c LENGTH 4 VALUE '@PB@'.
CONSTANTS icon_deselect_all TYPE c LENGTH 4 VALUE '@4D@'.
CONSTANTS icon_detail TYPE c LENGTH 4 VALUE '@3R@'.
CONSTANTS icon_dimension TYPE c LENGTH 4 VALUE '@9Q@'.
CONSTANTS icon_disconnect TYPE c LENGTH 4 VALUE '@GC@'.
CONSTANTS icon_display TYPE c LENGTH 4 VALUE '@10@'.
CONSTANTS icon_display_more TYPE c LENGTH 4 VALUE '@1E@'.
CONSTANTS icon_display_note TYPE c LENGTH 4 VALUE '@0L@'.
CONSTANTS icon_display_text TYPE c LENGTH 4 VALUE '@0P@'.
CONSTANTS icon_dispo_level TYPE c LENGTH 4 VALUE '@A2@'.
CONSTANTS icon_doc_header_detail TYPE c LENGTH 4 VALUE '@FA@'.
CONSTANTS icon_document TYPE c LENGTH 4 VALUE '@AR@'.
CONSTANTS icon_dropdownlist TYPE c LENGTH 4 VALUE '@R5@'.
CONSTANTS icon_dummy TYPE c LENGTH 4 VALUE '@00@'.
CONSTANTS icon_edit_file TYPE c LENGTH 4 VALUE '@HL@'.
CONSTANTS icon_element TYPE c LENGTH 4 VALUE '@HO@'.
CONSTANTS icon_eml TYPE c LENGTH 4 VALUE '@J8@'.
CONSTANTS icon_employee TYPE c LENGTH 4 VALUE '@5W@'.
CONSTANTS icon_enter_more TYPE c LENGTH 4 VALUE '@1F@'.
CONSTANTS icon_envelope_closed TYPE c LENGTH 4 VALUE '@E2@'.
CONSTANTS icon_equal TYPE c LENGTH 4 VALUE '@1G@'.
CONSTANTS icon_equal_green TYPE c LENGTH 4 VALUE '@20@'.
CONSTANTS icon_equal_red TYPE c LENGTH 4 VALUE '@2A@'.
CONSTANTS icon_error_protocol TYPE c LENGTH 4 VALUE '@DR@'.
CONSTANTS icon_execute_object TYPE c LENGTH 4 VALUE '@15@'.
CONSTANTS icon_expand TYPE c LENGTH 4 VALUE '@3S@'.
CONSTANTS icon_export TYPE c LENGTH 4 VALUE '@49@'.
CONSTANTS icon_extra TYPE c LENGTH 4 VALUE '@BU@'.
CONSTANTS icon_failure TYPE c LENGTH 4 VALUE '@03@'.
CONSTANTS icon_fast_entry TYPE c LENGTH 4 VALUE '@BQ@'.
CONSTANTS icon_field_with_text TYPE c LENGTH 4 VALUE '@OC@'.
CONSTANTS icon_filter TYPE c LENGTH 4 VALUE '@4G@'.
CONSTANTS icon_filter_undo TYPE c LENGTH 4 VALUE '@GD@'.
CONSTANTS icon_finite TYPE c LENGTH 4 VALUE '@CI@'.
CONSTANTS icon_folder TYPE c LENGTH 4 VALUE '@IH@'.
CONSTANTS icon_foreign_key TYPE c LENGTH 4 VALUE '@3V@'.
CONSTANTS icon_generate TYPE c LENGTH 4 VALUE '@39@'.
CONSTANTS icon_gis_pan TYPE c LENGTH 4 VALUE '@NK@'.
CONSTANTS icon_gis_promote TYPE c LENGTH 4 VALUE '@NM@'.
CONSTANTS icon_graduate TYPE c LENGTH 4 VALUE '@BT@'.
CONSTANTS icon_graphics TYPE c LENGTH 4 VALUE '@0N@'.
CONSTANTS icon_greater_equal_green TYPE c LENGTH 4 VALUE '@24@'.
CONSTANTS icon_greater_green TYPE c LENGTH 4 VALUE '@22@'.
CONSTANTS icon_green_light TYPE c LENGTH 4 VALUE '@08@'.
CONSTANTS icon_header TYPE c LENGTH 4 VALUE '@3P@'.
CONSTANTS icon_helpassistent_on TYPE c LENGTH 4 VALUE '@OF@'.
CONSTANTS icon_hint TYPE c LENGTH 4 VALUE '@AI@'.
CONSTANTS icon_history TYPE c LENGTH 4 VALUE '@96@'.
CONSTANTS icon_host TYPE c LENGTH 4 VALUE '@G6@'.
CONSTANTS icon_hr_position TYPE c LENGTH 4 VALUE '@LC@'.
CONSTANTS icon_htm TYPE c LENGTH 4 VALUE '@J4@'.
CONSTANTS icon_icon_list TYPE c LENGTH 4 VALUE '@3D@'.
CONSTANTS icon_idoc TYPE c LENGTH 4 VALUE '@G5@'.
CONSTANTS icon_import TYPE c LENGTH 4 VALUE '@48@'.
CONSTANTS icon_import_all_requests TYPE c LENGTH 4 VALUE '@K4@'.
CONSTANTS icon_import_transport_request TYPE c LENGTH 4 VALUE '@K5@'.
CONSTANTS icon_incoming_object TYPE c LENGTH 4 VALUE '@LR@'.
CONSTANTS icon_incomplete TYPE c LENGTH 4 VALUE '@02@'.
CONSTANTS icon_incompletion_log TYPE c LENGTH 4 VALUE '@KK@'.
CONSTANTS icon_information TYPE c LENGTH 4 VALUE '@0S@'.
CONSTANTS icon_insert_row TYPE c LENGTH 4 VALUE '@17@'.
CONSTANTS icon_inspection_characteristic TYPE c LENGTH 4 VALUE '@GV@'.
CONSTANTS icon_inspection_lot TYPE c LENGTH 4 VALUE '@EO@'.
CONSTANTS icon_inspection_method TYPE c LENGTH 4 VALUE '@GS@'.
CONSTANTS icon_intensify TYPE c LENGTH 4 VALUE '@4K@'.
CONSTANTS icon_intensify_critical TYPE c LENGTH 4 VALUE '@HC@'.
CONSTANTS icon_intensify_undo TYPE c LENGTH 4 VALUE '@GF@'.
CONSTANTS icon_interface TYPE c LENGTH 4 VALUE '@63@'.
CONSTANTS icon_interval_include_green TYPE c LENGTH 4 VALUE '@26@'.
CONSTANTS icon_interval_include_red TYPE c LENGTH 4 VALUE '@2G@'.
CONSTANTS icon_led_green TYPE c LENGTH 4 VALUE '@5B@'.
CONSTANTS icon_led_inactive TYPE c LENGTH 4 VALUE '@BZ@'.
CONSTANTS icon_led_red TYPE c LENGTH 4 VALUE '@5C@'.
CONSTANTS icon_led_yellow TYPE c LENGTH 4 VALUE '@5D@'.
CONSTANTS icon_less_equal_green TYPE c LENGTH 4 VALUE '@25@'.
CONSTANTS icon_less_green TYPE c LENGTH 4 VALUE '@23@'.
CONSTANTS icon_light_out TYPE c LENGTH 4 VALUE '@EB@'.
CONSTANTS icon_list TYPE c LENGTH 4 VALUE '@3W@'.
CONSTANTS icon_location TYPE c LENGTH 4 VALUE '@AF@'.
CONSTANTS icon_locked TYPE c LENGTH 4 VALUE '@06@'.
CONSTANTS icon_mail TYPE c LENGTH 4 VALUE '@1S@'.
CONSTANTS icon_mapped_relation TYPE c LENGTH 4 VALUE '@EY@'.
CONSTANTS icon_mass_change TYPE c LENGTH 4 VALUE '@HB@'.
CONSTANTS icon_mass_change_done TYPE c LENGTH 4 VALUE '@XP@'.
CONSTANTS icon_master_data_act TYPE c LENGTH 4 VALUE '@6V@'.
CONSTANTS icon_material TYPE c LENGTH 4 VALUE '@A6@'.
CONSTANTS icon_message_critical TYPE c LENGTH 4 VALUE '@1D@'.
CONSTANTS icon_message_critical_small TYPE c LENGTH 4 VALUE '@8N@'.
CONSTANTS icon_message_error TYPE c LENGTH 4 VALUE '@1B@'.
CONSTANTS icon_message_error_small TYPE c LENGTH 4 VALUE '@8O@'.
CONSTANTS icon_message_information TYPE c LENGTH 4 VALUE '@19@'.
CONSTANTS icon_message_information_small TYPE c LENGTH 4 VALUE '@8P@'.
CONSTANTS icon_message_question TYPE c LENGTH 4 VALUE '@1C@'.
CONSTANTS icon_message_question_small TYPE c LENGTH 4 VALUE '@8Q@'.
CONSTANTS icon_message_warning TYPE c LENGTH 4 VALUE '@1A@'.
CONSTANTS icon_message_warning_small TYPE c LENGTH 4 VALUE '@8R@'.
CONSTANTS icon_model TYPE c LENGTH 4 VALUE '@A7@'.
CONSTANTS icon_modification_create TYPE c LENGTH 4 VALUE '@97@'.
CONSTANTS icon_modification_overview TYPE c LENGTH 4 VALUE '@98@'.
CONSTANTS icon_modify TYPE c LENGTH 4 VALUE '@61@'.
CONSTANTS icon_money TYPE c LENGTH 4 VALUE '@AZ@'.
CONSTANTS icon_move TYPE c LENGTH 4 VALUE '@40@'.
CONSTANTS icon_negative TYPE c LENGTH 4 VALUE '@05@'.
CONSTANTS icon_new_task TYPE c LENGTH 4 VALUE '@LJ@'.
CONSTANTS icon_next_object TYPE c LENGTH 4 VALUE '@2S@'.
CONSTANTS icon_no_status TYPE c LENGTH 4 VALUE '@MG@'.
CONSTANTS icon_not_equal_green TYPE c LENGTH 4 VALUE '@21@'.
CONSTANTS icon_not_equal_red TYPE c LENGTH 4 VALUE '@2B@'.
CONSTANTS icon_object_folder TYPE c LENGTH 4 VALUE '@FP@'.
CONSTANTS icon_object_list TYPE c LENGTH 4 VALUE '@IG@'.
CONSTANTS icon_okay TYPE c LENGTH 4 VALUE '@0V@'.
CONSTANTS icon_oo_class_event TYPE c LENGTH 4 VALUE '@C6@'.
CONSTANTS icon_oo_connection TYPE c LENGTH 4 VALUE '@7N@'.
CONSTANTS icon_oo_event TYPE c LENGTH 4 VALUE '@7K@'.
CONSTANTS icon_oo_inst_event TYPE c LENGTH 4 VALUE '@C7@'.
CONSTANTS icon_oo_object TYPE c LENGTH 4 VALUE '@C9@'.
CONSTANTS icon_open TYPE c LENGTH 4 VALUE '@JJ@'.
CONSTANTS icon_open_folder TYPE c LENGTH 4 VALUE '@FO@'.
CONSTANTS icon_operation TYPE c LENGTH 4 VALUE '@9X@'.
CONSTANTS icon_order TYPE c LENGTH 4 VALUE '@9Z@'.
CONSTANTS icon_org_unit TYPE c LENGTH 4 VALUE '@BN@'.
CONSTANTS icon_other_object TYPE c LENGTH 4 VALUE '@2Q@'.
CONSTANTS icon_outgoing_object TYPE c LENGTH 4 VALUE '@LS@'.
CONSTANTS icon_outgoing_org_unit TYPE c LENGTH 4 VALUE '@LH@'.
CONSTANTS icon_overview TYPE c LENGTH 4 VALUE '@3Q@'.
CONSTANTS icon_package_application TYPE c LENGTH 4 VALUE '@QD@'.
CONSTANTS icon_package_standard TYPE c LENGTH 4 VALUE '@QC@'.
CONSTANTS icon_packing TYPE c LENGTH 4 VALUE '@E8@'.
CONSTANTS icon_page_left TYPE c LENGTH 4 VALUE '@0G@'.
CONSTANTS icon_page_right TYPE c LENGTH 4 VALUE '@0F@'.
CONSTANTS icon_parameter_result TYPE c LENGTH 4 VALUE '@7B@'.
CONSTANTS icon_partner TYPE c LENGTH 4 VALUE '@DG@'.
CONSTANTS icon_patient_smartcard TYPE c LENGTH 4 VALUE '@Q2@'.
CONSTANTS icon_pattern_include_green TYPE c LENGTH 4 VALUE '@28@'.
CONSTANTS icon_pattern_include_red TYPE c LENGTH 4 VALUE '@2I@'.
CONSTANTS icon_pdf TYPE c LENGTH 4 VALUE '@IT@'.
CONSTANTS icon_pdir_back TYPE c LENGTH 4 VALUE '@CF@'.
CONSTANTS icon_personal_help TYPE c LENGTH 4 VALUE '@4L@'.
CONSTANTS icon_physical_sample TYPE c LENGTH 4 VALUE '@GW@'.
CONSTANTS icon_plant TYPE c LENGTH 4 VALUE '@A8@'.
CONSTANTS icon_pm_insert TYPE c LENGTH 4 VALUE '@CL@'.
CONSTANTS icon_pm_press TYPE c LENGTH 4 VALUE '@CM@'.
CONSTANTS icon_position TYPE c LENGTH 4 VALUE '@3Y@'.
CONSTANTS icon_position_hr TYPE c LENGTH 4 VALUE '@BI@'.
CONSTANTS icon_positive TYPE c LENGTH 4 VALUE '@04@'.
CONSTANTS icon_ppe_snode TYPE c LENGTH 4 VALUE '@N1@'.
CONSTANTS icon_previous_object TYPE c LENGTH 4 VALUE '@2R@'.
CONSTANTS icon_price TYPE c LENGTH 4 VALUE '@FD@'.
CONSTANTS icon_price_analysis TYPE c LENGTH 4 VALUE '@Q6@'.
CONSTANTS icon_print TYPE c LENGTH 4 VALUE '@0X@'.
CONSTANTS icon_print_with_parameters TYPE c LENGTH 4 VALUE '@EW@'.
CONSTANTS icon_product_group TYPE c LENGTH 4 VALUE '@A9@'.
CONSTANTS icon_profit_center TYPE c LENGTH 4 VALUE '@D2@'.
CONSTANTS icon_proshare TYPE c LENGTH 4 VALUE '@1W@'.
CONSTANTS icon_protocol TYPE c LENGTH 4 VALUE '@DH@'.
CONSTANTS icon_ps_relationship TYPE c LENGTH 4 VALUE '@EH@'.
CONSTANTS icon_ps_wbs_element TYPE c LENGTH 4 VALUE '@ED@'.
CONSTANTS icon_qualify TYPE c LENGTH 4 VALUE '@5Z@'.
CONSTANTS icon_question TYPE c LENGTH 4 VALUE '@B0@'.
CONSTANTS icon_rating_minus TYPE c LENGTH 4 VALUE '@P6@'.
CONSTANTS icon_read_file TYPE c LENGTH 4 VALUE '@HJ@'.
CONSTANTS icon_red_light TYPE c LENGTH 4 VALUE '@0A@'.
CONSTANTS icon_reference_list TYPE c LENGTH 4 VALUE '@3A@'.
CONSTANTS icon_refresh TYPE c LENGTH 4 VALUE '@42@'.
CONSTANTS icon_reject TYPE c LENGTH 4 VALUE '@8Y@'.
CONSTANTS icon_relation TYPE c LENGTH 4 VALUE '@BW@'.
CONSTANTS icon_relationship TYPE c LENGTH 4 VALUE '@AA@'.
CONSTANTS icon_release TYPE c LENGTH 4 VALUE '@5Y@'.
CONSTANTS icon_remove_from_selection TYPE c LENGTH 4 VALUE '@GI@'.
CONSTANTS icon_remove_row TYPE c LENGTH 4 VALUE '@XQ@'.
CONSTANTS icon_replace TYPE c LENGTH 4 VALUE '@37@'.
CONSTANTS icon_report_template TYPE c LENGTH 4 VALUE '@QH@'.
CONSTANTS icon_resubmission TYPE c LENGTH 4 VALUE '@FR@'.
CONSTANTS icon_retail_store TYPE c LENGTH 4 VALUE '@TU@'.
CONSTANTS icon_sap TYPE c LENGTH 4 VALUE '@KR@'.
CONSTANTS icon_sap_server TYPE c LENGTH 4 VALUE '@X5@'.
CONSTANTS icon_search TYPE c LENGTH 4 VALUE '@13@'.
CONSTANTS icon_search_next TYPE c LENGTH 4 VALUE '@4E@'.
CONSTANTS icon_select_all TYPE c LENGTH 4 VALUE '@4B@'.
CONSTANTS icon_select_block TYPE c LENGTH 4 VALUE '@4C@'.
CONSTANTS icon_select_detail TYPE c LENGTH 4 VALUE '@16@'.
CONSTANTS icon_selection TYPE c LENGTH 4 VALUE '@7X@'.
CONSTANTS icon_set_b TYPE c LENGTH 4 VALUE '@8A@'.
CONSTANTS icon_set_copy_in_a TYPE c LENGTH 4 VALUE '@8F@'.
CONSTANTS icon_set_copy_in_b TYPE c LENGTH 4 VALUE '@8G@'.
CONSTANTS icon_set_state TYPE c LENGTH 4 VALUE '@3J@'.
CONSTANTS icon_set_sum TYPE c LENGTH 4 VALUE '@8B@'.
CONSTANTS icon_settings TYPE c LENGTH 4 VALUE '@XC@'.
CONSTANTS icon_shared_position TYPE c LENGTH 4 VALUE '@L9@'.
CONSTANTS icon_short_message TYPE c LENGTH 4 VALUE '@47@'.
CONSTANTS icon_show_events TYPE c LENGTH 4 VALUE '@ET@'.
CONSTANTS icon_show_external_jobs TYPE c LENGTH 4 VALUE '@EP@'.
CONSTANTS icon_simulate TYPE c LENGTH 4 VALUE '@8Z@'.
CONSTANTS icon_skip TYPE c LENGTH 4 VALUE '@43@'.
CONSTANTS icon_space TYPE c LENGTH 4 VALUE '@5F@'.
CONSTANTS icon_spool_request TYPE c LENGTH 4 VALUE '@EQ@'.
CONSTANTS icon_stack TYPE c LENGTH 4 VALUE '@3B@'.
CONSTANTS icon_statistics TYPE c LENGTH 4 VALUE '@FG@'.
CONSTANTS icon_status TYPE c LENGTH 4 VALUE '@EI@'.
CONSTANTS icon_status_alert TYPE c LENGTH 4 VALUE '@MD@'.
CONSTANTS icon_status_best TYPE c LENGTH 4 VALUE '@MF@'.
CONSTANTS icon_status_booked TYPE c LENGTH 4 VALUE '@B4@'.
CONSTANTS icon_status_critical TYPE c LENGTH 4 VALUE '@OJ@'.
CONSTANTS icon_status_ok TYPE c LENGTH 4 VALUE '@ME@'.
CONSTANTS icon_status_open TYPE c LENGTH 4 VALUE '@B3@'.
CONSTANTS icon_status_overview TYPE c LENGTH 4 VALUE '@F9@'.
CONSTANTS icon_status_partly_booked TYPE c LENGTH 4 VALUE '@B5@'.
CONSTANTS icon_status_reverse TYPE c LENGTH 4 VALUE '@B6@'.
CONSTANTS icon_stock TYPE c LENGTH 4 VALUE '@EL@'.
CONSTANTS icon_store TYPE c LENGTH 4 VALUE '@C0@'.
CONSTANTS icon_store_location TYPE c LENGTH 4 VALUE '@AC@'.
CONSTANTS icon_storno TYPE c LENGTH 4 VALUE '@BA@'.
CONSTANTS icon_structure TYPE c LENGTH 4 VALUE '@HP@'.
CONSTANTS icon_submit TYPE c LENGTH 4 VALUE '@8W@'.
CONSTANTS icon_sym_log_server TYPE c LENGTH 4 VALUE '@G9@'.
CONSTANTS icon_system_back TYPE c LENGTH 4 VALUE '@2M@'.
CONSTANTS icon_system_cancel TYPE c LENGTH 4 VALUE '@2O@'.
CONSTANTS icon_system_copy TYPE c LENGTH 4 VALUE '@2U@'.
CONSTANTS icon_system_end TYPE c LENGTH 4 VALUE '@2N@'.
CONSTANTS icon_system_extended_help TYPE c LENGTH 4 VALUE '@5E@'.
CONSTANTS icon_system_favorites TYPE c LENGTH 4 VALUE '@6D@'.
CONSTANTS icon_system_help TYPE c LENGTH 4 VALUE '@35@'.
CONSTANTS icon_system_local_copy TYPE c LENGTH 4 VALUE '@4O@'.
CONSTANTS icon_system_local_paste TYPE c LENGTH 4 VALUE '@4P@'.
CONSTANTS icon_system_okay TYPE c LENGTH 4 VALUE '@2K@'.
CONSTANTS icon_system_paste TYPE c LENGTH 4 VALUE '@2V@'.
CONSTANTS icon_system_play TYPE c LENGTH 4 VALUE '@I6@'.
CONSTANTS icon_system_possible_entries TYPE c LENGTH 4 VALUE '@4J@'.
CONSTANTS icon_system_save TYPE c LENGTH 4 VALUE '@2L@'.
CONSTANTS icon_system_shortcut TYPE c LENGTH 4 VALUE '@8T@'.
CONSTANTS icon_system_undo TYPE c LENGTH 4 VALUE '@2W@'.
CONSTANTS icon_target_group TYPE c LENGTH 4 VALUE '@PF@'.
CONSTANTS icon_task TYPE c LENGTH 4 VALUE '@BK@'.
CONSTANTS icon_tbh_hold TYPE c LENGTH 4 VALUE '@L3@'.
CONSTANTS icon_te_advance_payment TYPE c LENGTH 4 VALUE '@93@'.
CONSTANTS icon_terminated_org_unit TYPE c LENGTH 4 VALUE '@LF@'.
CONSTANTS icon_test TYPE c LENGTH 4 VALUE '@12@'.
CONSTANTS icon_text_act TYPE c LENGTH 4 VALUE '@6X@'.
CONSTANTS icon_text_field TYPE c LENGTH 4 VALUE '@OB@'.
CONSTANTS icon_text_ina TYPE c LENGTH 4 VALUE '@6Y@'.
CONSTANTS icon_time TYPE c LENGTH 4 VALUE '@1T@'.
CONSTANTS icon_toggle_display TYPE c LENGTH 4 VALUE '@K6@'.
CONSTANTS icon_toggle_display_change TYPE c LENGTH 4 VALUE '@3I@'.
CONSTANTS icon_tools TYPE c LENGTH 4 VALUE '@45@'.
CONSTANTS icon_total_left TYPE c LENGTH 4 VALUE '@0B@'.
CONSTANTS icon_transfer TYPE c LENGTH 4 VALUE '@KB@'.
CONSTANTS icon_transfer_structure TYPE c LENGTH 4 VALUE '@9W@'.
CONSTANTS icon_transfer_structure_ina TYPE c LENGTH 4 VALUE '@MU@'.
CONSTANTS icon_transport TYPE c LENGTH 4 VALUE '@4A@'.
CONSTANTS icon_transport_point TYPE c LENGTH 4 VALUE '@A5@'.
CONSTANTS icon_tree TYPE c LENGTH 4 VALUE '@3M@'.
CONSTANTS icon_trend_decreasing TYPE c LENGTH 4 VALUE '@M9@'.
CONSTANTS icon_trend_down TYPE c LENGTH 4 VALUE '@M8@'.
CONSTANTS icon_trend_rising TYPE c LENGTH 4 VALUE '@MB@'.
CONSTANTS icon_trend_unchanged TYPE c LENGTH 4 VALUE '@MA@'.
CONSTANTS icon_trend_up TYPE c LENGTH 4 VALUE '@MC@'.
CONSTANTS icon_unlocked TYPE c LENGTH 4 VALUE '@07@'.
CONSTANTS icon_unpack TYPE c LENGTH 4 VALUE '@E9@'.
CONSTANTS icon_unspecified_four TYPE c LENGTH 4 VALUE '@KZ@'.
CONSTANTS icon_unspecified_one TYPE c LENGTH 4 VALUE '@KW@'.
CONSTANTS icon_unspecified_three TYPE c LENGTH 4 VALUE '@KY@'.
CONSTANTS icon_unspecified_two TYPE c LENGTH 4 VALUE '@KX@'.
CONSTANTS icon_usergroup TYPE c LENGTH 4 VALUE '@ID@'.
CONSTANTS icon_variable TYPE c LENGTH 4 VALUE '@4M@'.
CONSTANTS icon_video TYPE c LENGTH 4 VALUE '@1X@'.
CONSTANTS icon_viewer_optical_archive TYPE c LENGTH 4 VALUE '@0U@'.
CONSTANTS icon_warehouse TYPE c LENGTH 4 VALUE '@A1@'.
CONSTANTS icon_warning TYPE c LENGTH 4 VALUE '@AH@'.
CONSTANTS icon_wd_context TYPE c LENGTH 4 VALUE '@S8@'.
CONSTANTS icon_wd_iframe TYPE c LENGTH 4 VALUE '@T9@'.
CONSTANTS icon_wd_table TYPE c LENGTH 4 VALUE '@T4@'.
CONSTANTS icon_wd_view TYPE c LENGTH 4 VALUE '@RN@'.
CONSTANTS icon_wd_view_area TYPE c LENGTH 4 VALUE '@RR@'.
CONSTANTS icon_wf_link TYPE c LENGTH 4 VALUE '@CQ@'.
CONSTANTS icon_wf_unlink TYPE c LENGTH 4 VALUE '@CR@'.
CONSTANTS icon_wf_workitem_completed TYPE c LENGTH 4 VALUE '@CX@'.
CONSTANTS icon_wf_workitem_error TYPE c LENGTH 4 VALUE '@CY@'.
CONSTANTS icon_wf_workitem_ol TYPE c LENGTH 4 VALUE '@E5@'.
CONSTANTS icon_wizard TYPE c LENGTH 4 VALUE '@BY@'.
CONSTANTS icon_workflow_activity TYPE c LENGTH 4 VALUE '@5H@'.
CONSTANTS icon_working_plan TYPE c LENGTH 4 VALUE '@AJ@'.
CONSTANTS icon_ws_start_whse_proc_backgr TYPE c LENGTH 4 VALUE '@LT@'.
CONSTANTS icon_ws_truck TYPE c LENGTH 4 VALUE '@7Q@'.
CONSTANTS icon_xls TYPE c LENGTH 4 VALUE '@J2@'.
CONSTANTS icon_xml_doc TYPE c LENGTH 4 VALUE '@R4@'.
CONSTANTS icon_yellow_light TYPE c LENGTH 4 VALUE '@09@'.