TYPE-POOL icon.

CONSTANTS icon_abap TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_led_green TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_led_inactive TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_led_red TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_led_yellow TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_message_information TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_okay TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_set_state TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_stack TYPE c LENGTH 4 VALUE 'ICON'.
CONSTANTS icon_system_help TYPE c LENGTH 4 VALUE 'ICON'.